version: '3.8'

services:
  # Frontend Service (Next.js)
  frontend:
    image: jagadeshvana/learnflow-frontend
    container_name: learnflow-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8081
      - NEXT_PUBLIC_API_URL=https://backend.intelskill.in
      # Limit Node.js memory to prevent crashes on small VPS
      - NODE_OPTIONS="--max-old-space-size=512"
    depends_on:
      - backend
    networks:
      - learnflow-network

  # Backend Service
  backend:
    image: jagadeshvana/learnflow-backend
    container_name: learnflow-backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - learnflow-network

  # Database Service
  mysql:
    image: mysql:8.0
    container_name: learnflow-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=auth_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      timeout: 20s
      retries: 10
    networks:
      - learnflow-network

  # SSL Certificate Service
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${CERTBOT_EMAIL} -d ${CERTBOT_DOMAIN1} -d ${CERTBOT_DOMAIN2} --agree-tos --no-eff-email
    networks:
      - learnflow-network

  # Watchtower Service (Auto-Update)
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
      - WATCHTOWER_CLEANUP=true
      - REPO_USER=${DOCKER_HUB_USERNAME}
      - REPO_PASS=${DOCKER_HUB_ACCESS_TOKEN}
    command: --interval 300
    networks:
      - learnflow-network

volumes:
  mysql_data:

networks:
  learnflow-network:
    driver: bridge
